/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RequestWebsiteBlock */

#ifndef _Included_RequestWebsiteBlock
#define _Included_RequestWebsiteBlock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RequestWebsiteBlock
 * Method:    requestWebsiteBlock
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_RequestWebsiteBlock_requestWebsiteBlock
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
